name: Check Pull Request

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - .github/workflows/pr-check.yml

jobs:
  setup:
    runs-on: ubuntu-latest
    steps: &common-steps
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - <<: *common-steps
      - name: Run ESLint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - <<: *common-steps
      - name: Run tests
        run: yarn test --ci --passWithNoTests